[build]
  publish = "dist"
  command = "npm run build"

[dev]
  framework = "vite"
  command = "npm run dev"
  port = 3000

[context.production.environment]
  NODE_ENV = "production"
  NPM_FLAGS = "--include=dev"
